ドコモ、au 売上要求処理 売上要求処理 (継続課金(定期・従量))
quipper/sbpayment.rb pull request #125
Opened 2021-01-30 08:34 UTC by tashirosota

本番で1年ほど問題なく動作しているためPR出させていただきます。

2021-02-12 07:20 UTC, MITSUBOSHI commented
@tashirosota 
レビューが滞っており申し訳ありません。レビューします。

2021-02-12 14:11 UTC, tashirosota commented
> @tashirosota
> レビューが滞っており申し訳ありません。レビューします。

ありがとうございます！
こちらですが、テストコードも近々追加させて頂きます🙇‍♂️

2021-02-14 02:51 UTC, tashirosota commented
@MITSUBOSHI 
遅くなりましたが、spec追加させて頂きました。
お手すきでご確認お願いいたします。

2021-02-17 07:03 UTC, ttokutake requested changes
まだ全部見れていないのですが、先にコメントだけさせてもらいましたのでご確認をお願いします 🙏 
また追ってレビューします。

2021-02-18 05:44 UTC, MITSUBOSHI requested changes
追いレビューしました。
こちらも確認・修正お願いします。

2021-02-18 05:44 UTC, MITSUBOSHI commented on lib/sbpayment/api/au/commit.rb
> +        key :tracking_id
Sbpayment::API::Sbpayment::SalesRequestと同様にPayOptionManageを定義してください。
https://github.com/quipper/sbpayment.rb/blob/18cc1ba14257c96073b096a931ea1eca02788c28/lib/sbpayment/api/credit/sales.rb#L21

2021-02-18 05:44 UTC, MITSUBOSHI commented on lib/sbpayment/api/docomo/commit.rb
> +        key :tracking_id
Sbpayment::API::Sbpayment::SalesRequestと同様にPayOptionManageを定義してください。
https://github.com/quipper/sbpayment.rb/blob/18cc1ba14257c96073b096a931ea1eca02788c28/lib/sbpayment/api/credit/sales.rb#L21

2021-02-18 05:44 UTC, MITSUBOSHI commented on spec/requests/api/au/authorization_spec.rb
> +require 'spec_helper'
https://github.com/quipper/sbpayment.rb/blob/master/.rspec#L2 で spec_helper を読み込んでいるため、
こちらのrequireを取り除いてください

2021-02-18 05:44 UTC, MITSUBOSHI commented on spec/requests/api/au/commit_spec.rb
> +require 'spec_helper'
https://github.com/quipper/sbpayment.rb/blob/master/.rspec#L2 で spec_helper を読み込んでいるため、
こちらのrequireを取り除いてください

2021-02-18 05:44 UTC, MITSUBOSHI commented on spec/requests/api/docomo/authorization_spec.rb
> +require 'spec_helper'
https://github.com/quipper/sbpayment.rb/blob/master/.rspec#L2 で spec_helper を読み込んでいるため、
こちらのrequireを取り除いてください

2021-02-18 05:44 UTC, MITSUBOSHI commented on spec/requests/api/docomo/commit_spec.rb
> +require 'spec_helper'
https://github.com/quipper/sbpayment.rb/blob/master/.rspec#L2 で spec_helper を読み込んでいるため、
こちらのrequireを取り除いてください

2021-02-18 05:44 UTC, MITSUBOSHI commented on spec/requests/api/docomo/commit_spec.rb
> +          # couldn't implement because trackng_id is nil
```suggestion
          # couldn't implement because tracking_id is nil
```

2021-02-18 05:44 UTC, MITSUBOSHI commented on spec/requests/api/docomo/authorization_spec.rb
> +        # couldn't implement because trackng_id is nil
```suggestion
        # couldn't implement because tracking_id is nil
```

2021-02-18 05:44 UTC, MITSUBOSHI commented on spec/requests/api/au/commit_spec.rb
> +          # couldn't implement because trackng_id is nil
```suggestion
          # couldn't implement because tracking_id is nil
```

2021-02-18 05:44 UTC, MITSUBOSHI commented on spec/requests/api/au/authorization_spec.rb
> +        # couldn't implement because trackng_id is nil
```suggestion
        # couldn't implement because tracking_id is nil
```

2021-02-18 06:03 UTC, MITSUBOSHI requested changes
こちらも合わせて確認・修正をお願いします。
(他に気になる点はありませんでした)

2021-02-18 06:03 UTC, MITSUBOSHI commented on spec/requests/api/au/authorization_spec.rb
> +describe 'au API behavior' do
こちらのPR (https://github.com/quipper/sbpayment.rb/pull/140)をマージした関係で各specのtoplevelで `RSpec.describe` としてくださいmm

```suggestion
RSpec.describe 'au API behavior' do
```

2021-02-18 06:03 UTC, MITSUBOSHI commented on spec/requests/api/au/commit_spec.rb
> +describe 'Au API behavior' do
こちらのPR (https://github.com/quipper/sbpayment.rb/pull/140)をマージした関係で各specのtoplevelで `RSpec.describe` としてくださいmm

```suggestion
RSpec.describe 'Au API behavior' do
```

2021-02-18 06:03 UTC, MITSUBOSHI commented on spec/requests/api/docomo/authorization_spec.rb
> +describe 'Docomo API behavior' do
こちらのPR (https://github.com/quipper/sbpayment.rb/pull/140)をマージした関係で各specのtoplevelで `RSpec.describe` としてくださいmm

```suggestion
RSpec.describe 'Docomo API behavior' do
```

2021-02-18 06:03 UTC, MITSUBOSHI commented on spec/requests/api/docomo/commit_spec.rb
> +describe 'Docomo API behavior' do
こちらのPR (https://github.com/quipper/sbpayment.rb/pull/140)をマージした関係で各specのtoplevelで `RSpec.describe` としてくださいmm

```suggestion
RSpec.describe 'Docomo API behavior' do
```

2021-02-18 13:10 UTC, tashirosota commented on README.md
> +ドコモケータイ払い 売上要求処理 (継続課金(定期・従量))    | `ST02-00201-401`   | `Sbpayment::API::Docomo::CommitRequest`        |
@ttokutake 
こちらに関してですが、既存実装のソフトバンクの00201を参考にしました。
既存のクラス名を変更してしまうのはちょっと事故が起きるきもしていますので、ご判断お伺いしたく思います。
https://github.com/quipper/sbpayment.rb/pull/141 PR作成致しましたので、こちらの判断が決定次第合わせて追従させて頂きます。
該当箇所: README.md:99
ソフトバンクまとめて支払い B 継続課金(定期) 確定処理     | `ST02-00201-405`   | `Sbpayment::API::Softbank::CommitRequest`

2021-02-18 13:23 UTC, tashirosota commented on spec/vcr_cassettes/au-commit.yml
> +---
ありがとうございます！！こちら修正しました。

2021-02-18 13:23 UTC, tashirosota commented on spec/requests/api/au/authorization_spec.rb
> +      context 'success' do
修正しました🙇‍♂️

2021-02-18 13:24 UTC, tashirosota commented on lib/sbpayment/api/au/commit.rb
> +        key :tracking_id
ありがとうございます！こちら追記致しました。

2021-02-18 13:26 UTC, tashirosota commented on spec/requests/api/au/authorization_spec.rb
> +require 'spec_helper'
ありがとうございます！！該当箇所修正しました!

2021-02-18 13:27 UTC, tashirosota commented on spec/requests/api/docomo/commit_spec.rb
> +          # couldn't implement because trackng_id is nil
ありがとうございます！該当箇所修正しました。

2021-02-18 13:27 UTC, tashirosota commented on spec/requests/api/au/authorization_spec.rb
> +describe 'au API behavior' do
ありがとうございます！該当箇所修正致しました。

2021-02-19 04:54 UTC, ttokutake commented on spec/vcr_cassettes/au-commit.yml
> +---
ありがとうございます 🙌

2021-02-19 04:54 UTC, ttokutake commented on spec/requests/api/au/authorization_spec.rb
> +      context 'success' do
ありがとうございます！

2021-02-19 04:59 UTC, ttokutake commented on README.md
> +ドコモケータイ払い 売上要求処理 (継続課金(定期・従量))    | `ST02-00201-401`   | `Sbpayment::API::Docomo::CommitRequest`        |
@tashirosota なるほど、ありがとうございます！
既存のソフトバンクの実装を見逃しておりました 🙏 
おっしゃる通りBreaking Changeとなってしまいますので、こちら判断のための時間をいただければと思います。
それまで修正はお待ちください。

2021-02-26 08:42 UTC, MITSUBOSHI commented on README.md
> +ドコモケータイ払い 売上要求処理 (継続課金(定期・従量))    | `ST02-00201-401`   | `Sbpayment::API::Docomo::CommitRequest`        |
@tashirosota 
https://github.com/quipper/sbpayment.rb/pull/141#pullrequestreview-599294717 の通り、こちらのPRでは「SalesRequest」にrenameをお願いします。
お手数ですがこちらのPRで新規追加された各ファイルのrenameもお願いします。

2021-02-27 20:28 UTC, tashirosota commented on README.md
> +ドコモケータイ払い 売上要求処理 (継続課金(定期・従量))    | `ST02-00201-401`   | `Sbpayment::API::Docomo::CommitRequest`        |
@MITSUBOSHI 
ありがとうございます！
こちら修正致しました！

2021-03-05 06:38 UTC, mopp approved these changes

2021-03-05 06:38 UTC, MITSUBOSHI approved these changes
@tashirosota
修正ありがとうございます！
マージまで長らく時間かかってしまっているため、細かい修正等は私たちの方でやっておきます。

2021-03-05 06:42 UTC, merged