Update CI rubies and test in latest too
quipper/sbpayment.rb pull request #137
Opened 2021-02-13 09:27 UTC by kachick

latest 指定しておけば常に最新のrubyでtestしてくれるという認識なので合ってますかね？一応入れとくと安心かなと

2021-02-18 05:50 UTC, mopp submitted a review, later dismissed
🍒

2021-02-18 05:54 UTC, MITSUBOSHI requested changes

2021-02-18 05:54 UTC, MITSUBOSHI commented on .circleci/config.yml
> +                - circleci/ruby:2.6.6-browsers
2.7系の追加もお願いします 🙏 
```suggestion
                - circleci/ruby:2.6.6-browsers
                - circleci/ruby:2.7.2-browsers
```

2021-02-18 07:40 UTC, kachick commented on .circleci/config.yml
> +                - circleci/ruby:2.6.6-browsers
お、了解しました。
あまり増やしてCI重くしてもあれかな？と思ったんですが、まぁそこまでのコストでも無いでしょうし足しちゃいますか。
頂いたパッチとして https://github.com/quipper/sbpayment.rb/pull/137/commits/4447926798410503f80e29ac91640fd90b74bf29 の様に取り入れておきました！

2021-02-18 10:58 UTC, MITSUBOSHI approved these changes
LGTM 👍

2021-02-18 23:08 UTC, mopp approved these changes

2021-02-18 23:08 UTC, merged

2021-02-19 01:58 UTC, kachick commented
Thank you!