Change Sbpayment::API::Softbank::CommitRequest to Sbpayment::API::Sof…
quipper/sbpayment.rb pull request #141
Opened 2021-02-18 13:00 UTC by tashirosota

…tbank::SalesRequest

2021-02-18 13:08 UTC, tashirosota commented on README.md
> +ソフトバンクまとめて支払い B 継続課金(定期) 売上要求     | `ST02-00201-405`   | `Sbpayment::API::Softbank::SalesRequest`        |
SbPayment側の仕様変更の可能性もありますが、ST02-00201-405に関しては確定処理ではなく売上要求でした。

2021-02-18 13:08 UTC, tashirosota commented on lib/sbpayment/api/softbank/commit.rb
> +      class CommitRequest < SalesRequest
既存実装に影響が出てしまうため、warningのみ表示して、下位互換担保致しました。

2021-02-18 13:08 UTC, tashirosota commented on lib/sbpayment/api/softbank/commit.rb
> +        key :pay_option_manage, class: PayOptionManage
pay_option_manageがなかったので追加しました。

2021-02-26 01:15 UTC, tashirosota commented on lib/sbpayment/api/softbank/commit.rb
> +      class CommitRequest < SalesRequest
`CommitRequest = SalesRequest` でも良いかと思ったのですが、warnを出したかったので上記実装になってます。

2021-02-26 02:31 UTC, kachick commented on lib/sbpayment/api/softbank/commit.rb
> +        end
* super を呼ばないと、 warn だけしかしない initialize になってしまうかな？と思いました。
* ruby のサポートバージョン的に大丈夫なら deprecate_constant 使っても良いのかな？と思いました。
  * https://docs.ruby-lang.org/ja/latest/method/Module/i/deprecate_constant.html
  * https://bugs.ruby-lang.org/issues/11398
  * https://rurema.clear-code.com/query:-/query:deprecate_constant/ 2.3 から対応してるのかな？ であれば先に https://github.com/quipper/sbpayment.rb/pull/132 を入れときたい気はしますね

2021-02-26 04:16 UTC, tashirosota commented on lib/sbpayment/api/softbank/commit.rb
> +        end
@kachick 
ありがとうございます！
そもそもの継承元である `Request` initializeでの何もしてなかったので、superは呼んでいません
ですが、`deprecate_constant` のほうが良さそうですね。
先んじで修正しておきます！

2021-02-26 08:40 UTC, MITSUBOSHI requested changes
@tashirosota 
reviewが遅くなり申し訳ありません。
https://github.com/quipper/sbpayment.rb/pull/125/files#r578403626 の件ですが、ご指摘どおり売上要求は「SalesRequest」が正しいです。
そのためこちらのPRは現在の修正通り進めて頂ければと思います。数点コメントをしたので、確認・修正をお願いします。

2021-02-27 20:07 UTC, tashirosota commented
@MITSUBOSHI @kachick 
Reviewありがとうございます。
諸々修正反映致しました。
また、specに関しては元々なかった && https://github.com/quipper/sbpayment.rb/pull/125 とconflictしてしまいそうですので、別途後日追加させて頂きます。

2021-02-27 20:17 UTC, tashirosota commented on lib/sbpayment/api/softbank/commit.rb
> +        end
@MITSUBOSHI 
parameter_definition.rbでのinitialize見落としておりましたっ。。ありがとうございます！

2021-03-05 06:36 UTC, MITSUBOSHI approved these changes
@tashirosota 
修正ありがとうございます！
マージまで長らく時間かかってしまっているため、細かい修正等は私たちの方でやっておきます。

2021-03-05 06:36 UTC, mopp approved these changes

2021-03-05 06:36 UTC, merged